package tedwester.convo.features.chat.data

import android.content.Context
import android.net.Uri
import android.provider.OpenableColumns
import android.webkit.MimeTypeMap
import java.io.File
import java.util.UUID
import tedwester.convo.features.chat.model.ChatAttachment

/**
 * Copies a content [Uri] into app-private storage so attachments survive
 * after the picker grants temporary access.
 */
object AttachmentStore {
    fun ingest(context: Context, uri: Uri): ChatAttachment? {
        val resolver = context.contentResolver
        val mimeType = resolver.getType(uri)
            ?: guessMimeFromName(queryDisplayName(context, uri))
        val displayName = queryDisplayName(context, uri)
            ?: defaultName(mimeType)
        val ext = extensionFor(displayName, mimeType)
        val dir = File(context.filesDir, "attachments").also { it.mkdirs() }
        val id = UUID.randomUUID().toString()
        val dest = File(dir, "$id.$ext")
        return runCatching {
            resolver.openInputStream(uri)?.use { input ->
                dest.outputStream().use { output -> input.copyTo(output) }
            } ?: return null
            ChatAttachment(
                id = id,
                path = dest.absolutePath,
                mimeType = mimeType,
                displayName = displayName,
            )
        }.getOrNull()
    }

    fun ingestFile(
        context: Context,
        file: File,
        mimeType: String? = null,
        displayName: String? = null,
        deleteSource: Boolean = false,
    ): ChatAttachment? {
        if (!file.exists() || !file.isFile) return null
        val resolvedMime = mimeType ?: guessMimeFromName(file.name) ?: "application/octet-stream"
        val resolvedName = displayName ?: file.name
        val ext = extensionFor(resolvedName, resolvedMime)
        val dir = File(context.filesDir, "attachments").also { it.mkdirs() }
        val id = UUID.randomUUID().toString()
        val dest = File(dir, "$id.$ext")
        return runCatching {
            file.inputStream().use { input ->
                dest.outputStream().use { output -> input.copyTo(output) }
            }
            if (deleteSource) file.delete()
            ChatAttachment(
                id = id,
                path = dest.absolutePath,
                mimeType = resolvedMime,
                displayName = resolvedName,
            )
        }.getOrNull()
    }

    /**
     * Persist raw generated bytes (TTS audio, generated image, …) as an
     * attachment under app-private storage and return the [ChatAttachment].
     */
    fun ingestBytes(
        context: Context,
        bytes: ByteArray,
        mimeType: String,
        displayName: String,
    ): ChatAttachment? {
        if (bytes.isEmpty()) return null
        val ext = extensionFor(displayName, mimeType)
        val dir = File(context.filesDir, "attachments").also { it.mkdirs() }
        val id = UUID.randomUUID().toString()
        val dest = File(dir, "$id.$ext")
        return runCatching {
            dest.outputStream().use { it.write(bytes) }
            ChatAttachment(
                id = id,
                path = dest.absolutePath,
                mimeType = mimeType,
                displayName = displayName,
            )
        }.getOrNull()
    }

    fun createCameraTempFile(context: Context): File {
        val dir = File(context.cacheDir, "camera").also { it.mkdirs() }
        return File(dir, "capture_${System.currentTimeMillis()}.jpg")
    }

    private fun queryDisplayName(context: Context, uri: Uri): String? {
        val cursor = context.contentResolver.query(
            uri,
            arrayOf(OpenableColumns.DISPLAY_NAME),
            null,
            null,
            null,
        ) ?: return uri.lastPathSegment
        return cursor.use {
            if (!it.moveToFirst()) return@use uri.lastPathSegment
            val idx = it.getColumnIndex(OpenableColumns.DISPLAY_NAME)
            if (idx < 0) uri.lastPathSegment else it.getString(idx)
        }
    }

    private fun defaultName(mimeType: String?): String =
        when {
            mimeType?.startsWith("image/") == true -> "image.jpg"
            mimeType?.startsWith("video/") == true -> "video.mp4"
            else -> "file"
        }

    private fun extensionFor(displayName: String, mimeType: String?): String {
        val fromName = displayName.substringAfterLast('.', missingDelimiterValue = "")
        if (fromName.isNotBlank() && fromName.length <= 8) return fromName
        val fromMime = mimeType
            ?.let { MimeTypeMap.getSingleton().getExtensionFromMimeType(it) }
        return fromMime?.takeIf { it.isNotBlank() } ?: "bin"
    }

    private fun guessMimeFromName(name: String?): String? {
        val ext = name?.substringAfterLast('.', "")?.lowercase()?.takeIf { it.isNotBlank() }
            ?: return null
        return MimeTypeMap.getSingleton().getMimeTypeFromExtension(ext)
    }
}
